# Generated by Django 5.1.6 on 2025-03-21 17:09

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=apps.utils.fields.CompressedFileField(
                blank=True, null=True, upload_to="product/images"
            ),
        ),
    ]
