# Generated by Django 5.1.6 on 2025-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product/images"),
        ),
    ]
