# Generated by Django 5.1.6 on 2025-04-07 20:40

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="product/images"
            ),
        ),
    ]
