# Generated by Django 5.1.6 on 2025-04-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_slider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="image",
        ),
    ]
