# Generated by Django 5.1.6 on 2025-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_remove_slider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="order",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="slider",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
