# Generated by Django 5.1.6 on 2025-04-23 18:07

import apps.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0008_alter_slider_order_alter_slider_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    apps.utils.fields.CompressedImageField(
                        blank=True, null=True, upload_to="product/images"
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.slider",
                    ),
                ),
            ],
        ),
    ]
