# Generated by Django 5.1.6 on 2025-04-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0009_sliderimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliderimage",
            name="slider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="category.slider",
            ),
        ),
    ]
