# Generated by Django 5.1.6 on 2025-05-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0012_banner_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description",
            field=models.TextField(),
        ),
    ]
