# Generated by Django 5.1.6 on 2025-04-07 20:40

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_image_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="products/images"
            ),
        ),
    ]
