# Generated by Django 5.1.6 on 2025-04-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_color_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
    ]
