# Generated by Django 5.1.6 on 2025-04-21 16:11

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="products/images"
            ),
        ),
    ]
