# Generated by Django 5.1.6 on 2025-04-21 16:28

import apps.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    apps.utils.fields.CompressedImageField(
                        blank=True, null=True, upload_to="products/images"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "images",
                "db_table": "products_images",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="pictures",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.image",
            ),
        ),
    ]
