# Generated by Django 5.1.6 on 2025-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_image_product_pictures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pictures",
        ),
        migrations.AddField(
            model_name="product",
            name="pictures",
            field=models.ManyToManyField(null=True, to="store.image"),
        ),
    ]
