# Generated by Django 5.1.6 on 2025-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_product_pictures_product_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pictures",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.image"
            ),
        ),
    ]
