# Generated by Django 5.1.6 on 2025-04-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_pictures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pictures",
        ),
        migrations.AddField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="store.product",
            ),
            preserve_default=False,
        ),
    ]
