# Generated by Django 5.1.6 on 2025-04-21 16:57

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_product_pictures_image_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=apps.utils.fields.CompressedImageField(
                blank=True, default=1, upload_to="products/images"
            ),
            preserve_default=False,
        ),
    ]
