# Generated by Django 5.1.6 on 2025-04-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_remove_slider_image"),
        ("store", "0011_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="slider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="category.slider",
            ),
            preserve_default=False,
        ),
    ]
