# Generated by Django 5.1.6 on 2025-04-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0008_alter_slider_order_alter_slider_title"),
        ("store", "0012_image_slider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="store.product",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="slider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="category.slider",
            ),
        ),
    ]
