# Generated by Django 5.1.6 on 2025-04-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_image_slider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="slider",
        ),
    ]
