# Generated by Django 5.1.6 on 2025-04-28 17:16

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_remove_image_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="color_picture",
            field=apps.utils.fields.CompressedImageField(
                blank=True, upload_to="products/images"
            ),
        ),
    ]
