# Generated by Django 5.1.6 on 2025-05-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_image_color_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
    ]
