# Generated by Django 5.1.6 on 2025-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_remove_product_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
