# Generated by Django 5.1.6 on 2025-04-22 12:36

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=apps.utils.fields.CompressedImageField(
                blank=True, null=True, upload_to="avatar"
            ),
        ),
    ]
